# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "[ANDROID_DEV]Deploy to Firebase App Distribution"
  lane :distribute_android_app_dev do
      firebase_app_distribution(
          app: ENV["FIREBASE_APP_ID_ANDROID"],
          groups: "beta",
          android_artifact_type: "APK",
          android_artifact_path: "../build/app/outputs/flutter-apk/app-development-release.apk",
          firebase_cli_token: ENV["FIREBASE_APP_TOKEN"]
      )
  end

  desc "[ANDROID_STG]Deploy to Firebase App Distribution"
  lane :distribute_android_app_stg do
      firebase_app_distribution(
          app: ENV["FIREBASE_APP_ID_ANDROID"],
          groups: "beta",
          android_artifact_type: "APK",
          android_artifact_path: "../build/app/outputs/flutter-apk/app-staging-release.apk",
          firebase_cli_token: ENV["FIREBASE_APP_TOKEN"]
      )
  end
end