name: "[ANDROID_STG] Deploy To Firebase App Distribution"

on: [ workflow_dispatch ]

jobs:
  deploy_to_firebase_app_distribution:
    name:  Deploy To Firebase App Distribution
    runs-on: macos-latest
    timeout-minutes: 20
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Set up repository
        uses: actions/checkout@v2
      
      - name: Set up flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.0.4'

      - name: Flutter clean
        working-directory: ${{ github.workspace }}
        run: flutter clean

      - name: Install Android Gems
        working-directory: ${{ github.workspace }}/android
        run: bundle install

      - name: Flutter get
        working-directory: ${{ github.workspace }}
        run: flutter pub get

      - name:  Create google service json
        run: |
          echo ${{ secrets.ANDROID_GOOGLE_SERVICE_STG }} | base64 --decode > ./android/app/src/staging/google-services.json

      - name: Create key.properties
        run: |
          echo ${{ secrets.ANDROID_UPLOAD_KEYSTORE }} | base64 -d > android/android_upload_keystore.jks
          echo 'storeFile=android_upload_keystore.jks' > android/key.properties
          echo 'storePassword=${{ secrets.ANDROID_STORE_PASSWORD }}' >> android/key.properties
          echo 'keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}' >> android/key.properties
          echo 'keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}' >> android/key.properties

      - name: Build APK
        working-directory: ${{ github.workspace }}
        run: flutter build apk --build-number=$GITHUB_RUN_NUMBER --target lib/main_staging.dart --flavor staging

      - name: Distribute to Firebase
        working-directory: ${{ github.workspace }}/android
        run: bundle exec fastlane distribute_android_app_stg
        env:
          FIREBASE_APP_ID_ANDROID: ${{ secrets.FIREBASE_APP_ID_ANDROID_STG }}
          FIREBASE_APP_TOKEN: ${{ secrets.FIREBASE_APP_TOKEN }}