name: "[IOS_DEV] Deploy To Firebase App Distribution"

on: [ workflow_dispatch ]

jobs:
  deploy_to_firebase_app_distribution:
    name:  Deploy To Firebase App Distribution
    runs-on: macos-latest
    timeout-minutes: 20
    steps:
      - name: Set up repository
        uses: actions/checkout@v2

      - name: Set Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      
      - name: Set up flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.0.4'

      - name: Flutter clean
        working-directory: ${{ github.workspace }}
        run: flutter clean

      - name: Install Ios Gems
        working-directory: ${{ github.workspace }}/ios
        run: bundle install

      - name: Flutter get
        working-directory: ${{ github.workspace }}
        run: flutter pub get

      - name: Build IPA
        working-directory: ${{ github.workspace }}
        run: flutter build ipa --export-method development --target lib/main_development.dart --flavor development

      - name: Distribute to Firebase
        working-directory: ${{ github.workspace }}/ios
        run: bundle exec fastlane distribute_ios_app_dev
        env:
          FIREBASE_APP_ID_IOS: ${{ secrets.FIREBASE_APP_ID_IOS_DEV }}
          FIREBASE_APP_TOKEN: ${{ secrets.FIREBASE_APP_TOKEN }}